tskmProject/Models/Ticket.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tskmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketReply = new HashSet<TicketReply>();
            this.Files = new HashSet<File>();
            this.TicketHistories = new HashSet<TicketHistory>();
        }
    
        public int ticketID { get; set; }
        public string ticketTitle { get; set; }
        public string ticketDetail { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int catagoryID { get; set; }
        public int statusID { get; set; }
        public int userID { get; set; }
        public string Place { get; set; }
        public string Tel { get; set; }
        public Nullable<int> AssigneeID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<TicketReply> TicketReply { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<TicketHistory> TicketHistories { get; set; }
        public virtual User Assignee { get; set; }
    }
}

tskmProject/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tskmProject.Models;

namespace tskmProject.Controllers
{
    public class FileController : Controller
    {
        public FileResult Get(long id)
        {
            using (tskmContainer db = new tskmContainer())
            {
                File file = db.Files.Find(id);
                return new FilePathResult(System.IO.Path.Combine(Server.MapPath("~/App_Data/uploads"), file.fileName), file.ContentType);
            }
        }
    }
}

tskmProject/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tskmProject.Models;
using System.Web.Security;

namespace tskmProject.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private tskmContainer db = new tskmContainer();

        // GET: Tickets
        //public class UploadController : TicketsController
        //{
        //    public ActionResult UploadDocument()
        //    {
        //        return View();
        //    }

        //    [HttpPost]
        //    public ActionResult Upload(HttpPostedFileBase file)
        //    {
        //        if (file != null && file.ContentLength > 0)
        //        {
        //            var fileName = Path.GetFileName(file.FileName);
        //            var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
        //            file.SaveAs(path);
        //        }

        //        return RedirectToAction("UploadDocument");
        //    }
        //}
        public ActionResult Index()
        {
            int userID = CurrentUser.GetUserID().Value;
            
            IEnumerable<Ticket> ticketList;
            if (CurrentUser.GetRoles().Any(x => x.Name == "Admin"))
            {
                ticketList = from Ticket in db.Tickets
                             select Ticket;
            }else
            {
                ticketList = from Ticket in db.Tickets
                             where Ticket.AssigneeID == userID || Ticket.userID == userID
                             select Ticket;
            }       
            return View(ticketList.ToList());
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            ViewBag.catagoryID = new SelectList(db.Catagories, "catagoryID", "catagoryName");
            return View();
        }


        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                int userID = CurrentUser.GetUserID().Value;

                ticket.userID = userID;
                ticket.CreatedDate = DateTime.Now;
                ticket.UpdatedDate = DateTime.Now;
                ticket.Status = db.Status.Single(x => x.statusName == "Opened");

                #region File Upload
                List<File> fileList = new List<Models.File>();
                for (int i = 0; i < Request.Files.Count; ++i)
                {
                    File fileUpload = FileHelper.Save(Request.Files[i], Server.MapPath("~/App_Data/uploads"));
                    fileList.Add(fileUpload);
                }

                var dbFiles = from dbFile in db.Files.ToList()
                             join file in fileList on dbFile.fileID equals file.fileID
                             select dbFile;
                ticket.Files = dbFiles.ToList();
                #endregion

                db.Tickets.Add(ticket);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.catagoryID = new SelectList(db.Catagories, "catagoryID", "catagoryName", ticket.catagoryID);
            ViewBag.statusID = new SelectList(db.Status, "statusID", "statusName", ticket.statusID);
            ViewBag.userID = new SelectList(db.Users, "userID", "userFname", ticket.userID);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.catagoryID = new SelectList(db.Catagories, "catagoryID", "catagoryName", ticket.catagoryID);
            ViewBag.statusID = new SelectList(db.Status, "statusID", "statusName", ticket.statusID);
            ViewBag.userID = new SelectList(db.Users, "userID", "userFname", ticket.userID);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ticketID,ticketTitle,contractChannel,ticketDetail,ticketDate,catagoryID,statusID,userID")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                int? userID = CurrentUser.GetUserID();

                if (userID != null)
                {
                    ticket.userID = userID.Value;
                    db.Entry(ticket).State = EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            ViewBag.catagoryID = new SelectList(db.Catagories, "catagoryID", "catagoryName", ticket.catagoryID);
            ViewBag.statusID = new SelectList(db.Status, "statusID", "statusName", ticket.statusID);
            ViewBag.userID = new SelectList(db.Users, "userID", "userFname", ticket.userID);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Assign(int id)
        {
            ViewBag.NewAssigneeID = new SelectList(db.Users, "userID", "userFname");
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }

            return View(new TicketHistory
            {
                TicketID = ticket.ticketID,
                OldAssigneeID = ticket.AssigneeID,
            });
        }

        [HttpPost]
        public ActionResult Assign(TicketHistory ticketHistory)
        {
            ticketHistory.CreatedByID = CurrentUser.GetUserID().Value;
            ticketHistory.CreatedDateTime = DateTime.Now;
            db.TicketHistories.Add(ticketHistory);

            Ticket ticket = db.Tickets.Find(ticketHistory.TicketID);
            ticket.AssigneeID = ticketHistory.NewAssigneeID;
            ticket.UpdatedDate = DateTime.Now;
            ticket.Status = db.Status.Single(x => x.statusName == "In Progress");

            db.SaveChanges();

            return RedirectToAction("Details", new { id = ticketHistory.TicketID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reply(TicketReply reply)
        {
            if (ModelState.IsValid)
            {
                reply.userID = CurrentUser.GetUserID().Value;
                reply.replyDate = DateTime.Now;
                db.TicketReplies.Add(reply);
                db.SaveChanges();
            }

            return RedirectToAction("Details", new { id = reply.ticketID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CloseTicket(Ticket ticket)
        {
            Ticket dbTicket = db.Tickets.Find(ticket.ticketID);
            ticket.UpdatedDate = DateTime.Now;

            if (CurrentUser.GetUserID().Value == dbTicket.userID)
            {
                dbTicket.Status = db.Status.Single(x=> x.statusName == "Closed");
            }
            else if (CurrentUser.GetRoles().Any(x => x.Name == "Admin" || x.Name == "IT User"))
            {
                dbTicket.Status = db.Status.Single(x => x.statusName == "Waiting for closing");
            }
            db.SaveChanges();
            return RedirectToAction("Details", new { id = ticket.ticketID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReopenTicket(Ticket ticket)
        {
            Ticket dbTicket = db.Tickets.Find(ticket.ticketID);
            ticket.UpdatedDate = DateTime.Now;

            if (dbTicket.AssigneeID != null)
            {
                dbTicket.Status = db.Status.Single(x => x.statusName == "In Progress");
            }
            else
            {
                dbTicket.Status = db.Status.Single(x => x.statusName == "Opened");
            }

            db.SaveChanges();

            return RedirectToAction("Details", new { id = ticket.ticketID });
        }
    }
}

tskmProject/Views/Tickets/Assign.cshtml
@model tskmProject.Models.TicketHistory
@{
    ViewBag.Title = "มอบหมาย";
}
@using (Html.BeginForm("Assign", "Tickets", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.TicketID)
    @Html.HiddenFor(model => model.OldAssigneeID)
    <div class="row">
        <h3 class="page-header">มอบหมายงาน</h3>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(model => model.NewAssigneeID, "มอบหมาย", new { @class = "col-md-2 control-label" })
                <div class="col-md-3">
                    @Html.DropDownList("NewAssigneeID", null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NewAssigneeID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">ความคิดเห็น</label>
                <div class="col-md-5">
                    @Html.TextAreaFor(x => x.Comment, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Comment, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-3">
                    <button type="submit" value="Create" class="btn btn-default">ยืนยันข้อมูล</button>
                    @Html.ActionLink("กลับสู่หน้าหลัก", "Index")
                </div>
            </div>
        </div>
    </div>
}

tskmProject/Views/Tickets/Create.cshtml
@model tskmProject.Models.Ticket

@{
    ViewBag.Title = "สร้างใบงาน";
}

@using (Html.BeginForm("Create", "Tickets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h3 class="page-header">สร้างใบงาน</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="panel panel-default">
            <div class="panel-body">
                <br />
                <div class="form-group">
                    @Html.LabelFor(m => m.ticketTitle, "ชื่อเรื่อง", new { @class = "col-md-2 control-label" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.ticketTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ticketTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.catagoryID, "ประเภทใบงาน", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.DropDownList("catagoryID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.catagoryID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ticketDetail, "รายละเอียดงาน", new { @class = "col-md-2 control-label" })
                    <div class="col-md-4">
                        @Html.TextAreaFor(model => model.ticketDetail, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ticketDetail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Place, "สถานที่", new { @class = "col-md-2 control-label" })
                    <div class="col-md-4">
                        @Html.TextAreaFor(model => model.Place, 3, 50, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Tel, "เบอร์ติดต่อ", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label">เอกสารประกอบ</label>
                    <div class="col-md-10">
                        <input type="file" name="FileUpload" multiple>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" value="Create" class="btn btn-default">บันทึกใบงาน</button>
                        @Html.ActionLink("กลับสู่หน้าหลัก", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

tskmProject/Views/Tickets/Details.cshtml
@model tskmProject.Models.Ticket
@{
    ViewBag.Title = "แสดงรายละเอียด";
}
<div class="row">
    <h3 class="page-header"> @Model.ticketTitle</h3>
</div>
<div class="panel panel-primary">
    <div class="panel panel-heading">
        <b>รายละเอียด</b>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt class="col-md-4">
                @Html.LabelFor(model => model.ticketTitle, "เรื่อง")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ticketTitle)
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.Catagory.catagoryName, "ประเภทใบงาน")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Catagory.catagoryName)
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.ticketDetail, "รายละเอียดใบงาน")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ticketDetail)
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.Assignee, "ผู้รับมอบหมาย")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Assignee.userFname)
                @if (CurrentUser.GetRoles().Any(x => x.Name == "Admin" || x.Name == "IT Manager" || (x.Name == "IT User" && @Model.AssigneeID == CurrentUser.GetUserID())))
                {
                    @Html.ActionLink("มอบหมาย", "Assign", new { id = @Model.ticketID }, new { @class = "glyphicon glyphicon-user" , role = "button"})
                }
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.CreatedDate, "วันที่เปิดใบงาน")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.Status.statusName, "สถานะใบงาน")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Status.statusName)
            </dd>
            <dt class="col-md-4">
                @Html.LabelFor(model => model.User.username, "ผู้สร้าง")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.User.username)
            </dd>
            <dt class="col-md-4">
                ไฟล์เพิ่มเติม
            </dt>
            <dd>
                @{ int itemNo = 1; }
                @foreach (var item in Model.Files)
                {
                    <a href="@Url.Action("Get", "File", new { id = item.fileID })">ไฟล์ที่ @itemNo</a><br>
                    ++itemNo;
                }
            </dd>
        </dl>
        <div class="row">
            <div class="col-md-5">
                @if (!(Model.Status.statusName == "Closed" || (Model.Status.statusName == "Waiting for closing" && CurrentUser.GetRoles().Any(x => x.Name == "Admin" || x.Name == "IT User"))))
                {
                    using (Html.BeginForm("CloseTicket", "Tickets"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.ticketID)
                        <button type="submit" class="btn btn-success">Close Ticket</button>
                    }
                }
                @if (Model.Status.statusName == "Closed" && (CurrentUser.GetRoles().Any(x => x.Name == "Admin" || Model.userID == CurrentUser.GetUserID().Value)))
                {
                    using (Html.BeginForm("ReopenTicket", "Tickets"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.ticketID)
                        <button type="submit" class="btn btn-warning">Reopen Ticket</button>
                    }
                }
            </div>
        </div>
    </div>
</div>
@foreach (var item in @Model.TicketReply.Select(x => new { Title = "ตอบกลับ โดย " + x.User.userFname, Message = x.replyDetail, CreatedDateTime = x.replyDate })
    .Union(@Model.TicketHistories.Select(x => new { Title = "มอบหมายงาน โดย " + x.CreatedBy.userFname, Message = "ผู้รับมอบหมายงาน -> " + x.NewAssignee.userFname, CreatedDateTime = x.CreatedDateTime }))
    .OrderBy(x => x.CreatedDateTime))
{
    <div class="panel panel-info">
        <div class="panel-heading">
            <b>@item.Title (@item.CreatedDateTime)</b>
        </div>
        <div class="panel-body">
            @item.Message
        </div>
    </div>
}
@using (Html.BeginForm("Reply", "Tickets"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true);
    <div class="panel panel-warning">
        <div class="panel-heading">
            <b>ตอบกลับ</b>
        </div>
        <div class="panel-body">
            @Html.Hidden("ticketID", @Model.ticketID)
            <div class="form-group">
                <label>รายละเอียด:</label>
                @Html.TextArea("replyDetail", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <button class="btn btn-default" type="submit">ตอบ</button>
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-md-12 text-center">
        @Html.ActionLink("กลับสู่หน้าหลัก", "Index")
    </div>
</div>

tskmProject/Views/Tickets/Index.cshtml
@model IEnumerable<tskmProject.Models.Ticket>

@{
    ViewBag.Title = "รายการใบงาน";
}

<div class="row">
    <h3 class="page-header">รายการใบงาน</h3>
</div>
@Html.ActionLink("สร้างใบงาน", "Create", null, new { @class = "btn btn-default", role = "button" })
<br />
<br />

        <table class="table table-striped">
    <tr>
        <th>รหัสใบงาน</th>
        <th>ชื่อใบงาน</th>
        <th>ประเภทใบงาน</th>
        <th>ผู้สร้าง</th>
        <th>วันที่สร้างใบงาน</th>
        <th>ผู้รับมอบหมายงาน</th>
        <th>สถานะใบงาน</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @String.Format("{0:D5}", item.ticketID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ticketTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory.catagoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.userFname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assignee.userFname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.statusName)
            </td>

            <td>
                @Html.ActionLink("รายละเอียด", "Details", new { id = item.ticketID }, new { @class = "glyphicon glyphicon-search", role = "button" }) 
                
            </td>
        </tr>
    }

</table>